Research.Web/Controllers/FiscalScheduleController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Research.Data;
using Research.Services;
using Research.Services.Logging;
using Research.Services.Media;
using Research.Services.Security;
using Research.Web.Factories;
using Research.Web.Extensions;
using Research.Web.Framework.Mvc.Filters;
using Research.Web.Models.FiscalSchedules;
using Research.Services.Common;
using Research.Web.Framework.Mvc;
using Research.Services.FiscalSchedules;

namespace Research.Web.Controllers
{ 
    public partial class FiscalScheduleController : BaseAdminController
    {
        #region Fields

        private readonly IUserActivityService _userActivityService;
        private readonly IUserService _userService;
        private readonly IPermissionService _permissionService;
        private readonly IFiscalScheduleModelFactory _fiscalScheduleModelFactory;
        private readonly IFiscalScheduleService _fiscalScheduleService;

        #endregion Fields

        #region Ctor

        public FiscalScheduleController(IUserActivityService userActivityService,
            IUserService userService,
            IPermissionService permissionService,
            IFiscalScheduleModelFactory fiscalScheduleModelFactory,
            IFiscalScheduleService fiscalScheduleService)
        {
            this._userActivityService = userActivityService;
            this._userService = userService;
            this._permissionService = permissionService;
            this._fiscalScheduleModelFactory = fiscalScheduleModelFactory;
            this._fiscalScheduleService = fiscalScheduleService;
        }

        #endregion

        #region List

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageFiscalSchedules))
                return AccessDeniedView();

            //prepare model
            var model = _fiscalScheduleModelFactory.PrepareFiscalScheduleSearchModel(new FiscalScheduleSearchModel());

            return View(model);
        }

        [HttpPost, ActionName("List")]
        public virtual IActionResult List(FiscalScheduleSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageFiscalSchedules))
                return AccessDeniedKendoGridJson();

            //prepare model
            var model = _fiscalScheduleModelFactory.PrepareFiscalScheduleListModel(searchModel);
           // var model = _fiscalScheduleModelFactory.PrepareFiscalScheduleListModel(searchModel);

            return Json(model);
            //return View(model);
        }

        #endregion

        #region Create / Edit / Delete
        [HttpGet, ActionName("Create")]
        public virtual IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageFiscalSchedules))
                return AccessDeniedView();

            //prepare model
            var model = _fiscalScheduleModelFactory.PrepareFiscalScheduleModel(new FiscalScheduleModel(), null);

            return View(model);
        }
        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Create(FiscalScheduleModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageFiscalSchedules))
                return AccessDeniedView();
            var fiscalSchedule = model.ToEntity<FiscalSchedule>();
            fiscalSchedule.ClosingDate = Convert.ToDateTime(model.ClosingDate).AddYears(-543);
            fiscalSchedule.OpeningDate = Convert.ToDateTime(model.OpeningDate).AddYears(-543);
            if (ModelState.IsValid)
            {
                fiscalSchedule.FiscalYear = model.FiscalYear;
                fiscalSchedule.FiscalCode = model.FiscalCode;
                fiscalSchedule.FiscalTimes = model.FiscalTimes;
                fiscalSchedule.ScholarName = model.ScholarName;

                _fiscalScheduleService.InsertFiscalSchedule(fiscalSchedule);

                return continueEditing ? RedirectToAction("Edit", new { fiscalSchedule.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = _fiscalScheduleModelFactory.PrepareFiscalScheduleModel(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }


        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageFiscalSchedules))
                return AccessDeniedView();

            //try to get a fiscalSchedule with the specified id
            var fiscalSchedule = _fiscalScheduleService.GetFiscalScheduleById(id);
            if (fiscalSchedule == null)
                return RedirectToAction("List");

            //prepare model
            var model = _fiscalScheduleModelFactory.PrepareFiscalScheduleModel(null, fiscalSchedule);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Edit(FiscalScheduleModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageFiscalSchedules))
                return AccessDeniedView();

            //try to get a fiscalSchedule with the specified id
            var fiscalSchedule = _fiscalScheduleService.GetFiscalScheduleById(model.Id);
            if (fiscalSchedule == null)
                return RedirectToAction("List");
            fiscalSchedule = model.ToEntity(fiscalSchedule);
            fiscalSchedule.ClosingDate = Convert.ToDateTime(model.ClosingDate).AddYears(-543);
            fiscalSchedule.OpeningDate = Convert.ToDateTime(model.OpeningDate).AddYears(-543);
            if (ModelState.IsValid)
            {
                fiscalSchedule.FiscalYear = model.FiscalYear;
                fiscalSchedule.FiscalCode = model.FiscalCode;
                fiscalSchedule.FiscalTimes = model.FiscalTimes;
                fiscalSchedule.ScholarName = model.ScholarName;
                _fiscalScheduleService.UpdateFiscalSchedule(fiscalSchedule);

                return continueEditing ? RedirectToAction("Edit", new { fiscalSchedule.Id }) : RedirectToAction("List");

            }

            //prepare model
            model = _fiscalScheduleModelFactory.PrepareFiscalScheduleModel(model, fiscalSchedule, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        public virtual IActionResult Info(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageFiscalSchedules))
                return AccessDeniedView();

            //try to get a fiscalSchedule with the specified id
            var fiscalSchedule = _fiscalScheduleService.GetFiscalScheduleById(id);
            if (fiscalSchedule == null)
                return RedirectToAction("List");

            //prepare model
            var model = _fiscalScheduleModelFactory.PrepareFiscalScheduleModel(null, fiscalSchedule);

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageFiscalSchedules))
                return AccessDeniedView();

            //try to get a fiscalSchedule with the specified id
            var fiscalSchedule = _fiscalScheduleService.GetFiscalScheduleById(id)
                ?? throw new ArgumentException("ไม่พบวันเปิดรับข้อเสนอโครงการวิจัย");

            fiscalSchedule.Deleted = true;
            _fiscalScheduleService.UpdateFiscalSchedule(fiscalSchedule);

            return new NullJsonResult();
        }

        #endregion

    }
}

Research.Web/Views/FiscalSchedule/Create.cshtml
@model FiscalScheduleModel

@{
    ViewBag.Title = "กำหนดวันเปิดรับข้อเสนอโครงการวิจัย";
}

<form asp-controller="FiscalSchedule" asp-action="Create" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            เพิ่มวันเปิดรับข้อเสนอโครงการวิจัย
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">กลับสู่รายการวันเปิดรับข้อเสนอโครงการวิจัย</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึก
            </button>
            @*<button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึกและทำรายการต่อ
            </button>*@
            @*@await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.FiscalScheduleDetailsButtons, additionalData = Model })*@
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

Research.Web/Views/FiscalSchedule/Edit.cshtml
@model FiscalScheduleModel

@{
    ViewBag.Title = "วันเปิดรับข้อเสนอโครงการวิจัย";
}

<form asp-controller="Fiscalschedule" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            แก้ไขวันเปิดรับข้อเสนอโครงการวิจัย
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">กลับสู่รายการวันเปิดรับข้อเสนอโครงการวิจัย</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึก
            </button>
            @*<button type="submit" name="save-continue" class="btn bg-blue">
            <i class="fa fa-floppy-o"></i>
            บันทึกและทำรายการต่อ
        </button>*@
            @*@await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.FiscalscheduleDetailsButtons, additionalData = Model })*@
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

Research.Web/Views/FiscalSchedule/List.cshtml
@model FiscalScheduleSearchModel

@{
    //page title
    ViewBag.Title = "รายการวันเปิดรับข้อเสนอโครงการวิจัย";
    //active menu item (system name)
    //Html.SetActiveMenuItemSystemName("FiscalSchedule");
}

@*<form asp-controller="FiscalSchedule" asp-action="List" method="post" id="fiscalschedules-form">*@
    <div class="content-header clearfix">
        <h1 class="pull-left">
            รายการวันเปิดรับข้อเสนอโครงการวิจัย
        </h1>
        <div class="pull-right">
            &nbsp;
            <a asp-action="Create" class="btn btn-primary">เพิ่มรหัสวันเปิดรับข้อเสนอโครงการวิจัย</a>
            @*@await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.FiscalScheduleListButtons })*@
        </div>
    </div>

    <div class="content">
        <div class="panel-group">
            <div class="panel panel-default panel-search">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="ScholarName" />
                                </div>
                                <div class="col-md-8">
                                    <nop-editor asp-for="ScholarName"  />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="button" id="search-fiscalschedules" class="btn btn-primary btn-search">
                                        <i class="fa fa-search"></i>
                                        ค้นหา
                                    </button>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="fiscalschedules-grid"></div>

                    <script>
                        $(document).ready(function() {
                            $("#fiscalschedules-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("List", "FiscalSchedule"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: function() {
                                                var data = {
                                                    ScholarName: $('#ScholarName').val(),
                                                };
                                                addAntiForgeryToken(data);
                                                return data;
                                            }
                                        },
                                        destroy: {
                                            url: "@Html.Raw(Url.Action("Delete", "FiscalSchedule"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: addAntiForgeryToken
                                        }
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors",
                                        model: {
                                            id: "Id",
                                            fields: {
                                                Name: { editable: true, type: "string" },
                                                FiscalYear: { editable: true, type: "number" },
                                                Id: { editable: false, type: "number" }
                                            }
                                        }
                                    },
                                    requestEnd: function(e) {
                                        if (e.type == "create" || e.type == "update") {
                                            this.read();
                                        }
                                    },
                                    error: function(e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    pageSize: @(Model.PageSize),
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                pageable: {
                                    refresh: true,
                                    pageSizes: [@(Model.AvailablePageSizes)],
                                    @await Html.PartialAsync("_GridPagerMessages")
                                },
                                editable: {
                                    confirmation: "คุณต้องการที่จะลบรายการใช่หรือไม่",
                                    mode: "inline"
                                },
                                scrollable: false,
                                columns: [
                                    {
                                        field: "FiscalYear",
                                        title: "ปี",
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                        width: 100
                                    }, {
                                        field: "FiscalTimes",
                                        title: "ครั้งที่",
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                        width: 75
                                    }, {
                                        field: "ScholarName",
                                        title: "ชื่อทุนวิจัย",
                                        width: 300
                                    }, {
                                        field: "OpeningDateName",
                                        title: "วันเปิดรับ",
                                        width: 150,
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                    }, {
                                        field: "ClosingDateName",
                                        title: "วันปิดรับ",
                                        width: 150,
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                    }, {
                                        field: "Id",
                                        title: "แก้ไข",
                                        width: 150,
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                        template: '<a class="btn btn-default" href="/FiscalSchedule/Edit/#=Id#"><i class="fa fa-pencil"> แก้ไขรายการ</i></a>'  
                                    }, {
                                        command: { name: "destroy", text: "ลบรายการ" },
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                        title: "ลบ",
                                        width: 100
                                    }
                                ]
                            });
                        });
                    </script>
                    <script>
                        $(document).ready(function () {
                            $('#search-fiscalschedules').click(function () {
                                //refresh grid
                                var grid = $("#fiscalschedules-grid").data('kendoGrid');
                                grid.dataSource.read();

                                //return false to don't reload a page
                                return false;
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
@*</form>*@

Research.Web/Views/FiscalSchedule/_CreateOrUpdate.cshtml
@model FiscalScheduleModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-sm-3">
                            <nop-label asp-for="FiscalCode" />
                        </div>
                        <div class="col-sm-9">
                            <label>@Model.FiscalCode</label>
                            <input asp-for="FiscalCode" type="hidden" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">
                            <nop-label asp-for="FiscalYear" />
                        </div>
                        <div class="col-sm-9">
                            <nop-select asp-for="FiscalYear" asp-items="Model.AvailableFiscalYears" />
                            <span asp-validation-for="FiscalYear"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">
                            <nop-label asp-for="FiscalTimes" />
                        </div>
                        <div class="col-sm-9">
                            <nop-editor asp-for="FiscalTimes" />
                            <span asp-validation-for="FiscalTimes"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">
                            <nop-label asp-for="ScholarName" />
                        </div>
                        <div class="col-sm-9">
                            <nop-editor asp-for="ScholarName" asp-required="true" />
                            <span asp-validation-for="ScholarName"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">

                            <nop-label asp-for="OpeningDate" />
                        </div>
                        <div class="col-sm-9">
                            <nop-editor asp-for="OpeningDate" asp-required="true" />
                            <span asp-validation-for="OpeningDate"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">
                            <nop-label asp-for="ClosingDate" />
                        </div>
                        <div class="col-sm-9">
                            
                            <nop-editor asp-for="ClosingDate" asp-required="true" />
                            <span asp-validation-for="ClosingDate"></span>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
 
</div>