Research.Web/Controllers/DownloadController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Research.Core;
using Research.Data;
using Research.Infrastructure;
using Research.Services.Media;

namespace Research.Web.Controllers
{
    public partial class DownloadController : BaseAdminController
    {
        #region Fields

        private readonly IDownloadService _downloadService;
        private readonly IResearchFileProvider _fileProvider;

        #endregion

        #region Ctor

        public DownloadController(IDownloadService downloadService,
            IResearchFileProvider fileProvider)
        {
            this._downloadService = downloadService;
            this._fileProvider = fileProvider;
        }

        #endregion

        #region Methods

        public virtual IActionResult DownloadFile(Guid downloadGuid)
        {
            var download = _downloadService.GetDownloadByGuid(downloadGuid);
            if (download == null)
                return Content("No download record found with the specified id");

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

            //use stored data
            if (download.DownloadBinary == null)
                return Content($"Download data is not available any more. Download GD={download.Id}");

            var fileName = !string.IsNullOrWhiteSpace(download.Filename) ? download.Filename : download.Id.ToString();
            var contentType = !string.IsNullOrWhiteSpace(download.ContentType)
                ? download.ContentType
                : MimeTypes.ApplicationOctetStream;
            return new FileContentResult(download.DownloadBinary, contentType)
            {
                FileDownloadName = fileName + download.Extension
            };
        }

        [HttpPost]
        //do not validate request token (XSRF)
        //[AdminAntiForgery(true)] 
        public virtual IActionResult SaveDownloadUrl(string downloadUrl)
        {
            //insert
            var download = new Download
            {
                DownloadGuid = Guid.NewGuid(),
                UseDownloadUrl = true,
                DownloadUrl = downloadUrl,
                IsNew = true
              };
            _downloadService.InsertDownload(download);

            return Json(new { downloadId = download.Id });
        }

        [HttpPost]
        //do not validate request token (XSRF)
       // [AdminAntiForgery(true)]
        public virtual IActionResult AsyncUpload()
        {
            var httpPostedFile = Request.Form.Files.FirstOrDefault();
            if (httpPostedFile == null)
            {
                return Json(new
                {
                    success = false,
                    message = "No file uploaded",
                    downloadGuid = Guid.Empty
                });
            }

            var fileBinary = httpPostedFile.GetDownloadBits();

            var qqFileNameParameter = "qqfilename";
            var fileName = httpPostedFile.FileName;
            if (string.IsNullOrEmpty(fileName) && Request.Form.ContainsKey(qqFileNameParameter))
                fileName = Request.Form[qqFileNameParameter].ToString();
            //remove path (passed in IE)
            fileName = _fileProvider.GetFileName(fileName);

            var contentType = httpPostedFile.ContentType;

            var fileExtension = _fileProvider.GetFileExtension(fileName);
            if (!string.IsNullOrEmpty(fileExtension))
                fileExtension = fileExtension.ToLowerInvariant();

            var download = new Download
            {
                DownloadGuid = Guid.NewGuid(),
                UseDownloadUrl = false,
                DownloadUrl = string.Empty,
                DownloadBinary = fileBinary,
                ContentType = contentType,
                //we store filename without extension for downloads
                Filename = _fileProvider.GetFileNameWithoutExtension(fileName),
                Extension = fileExtension,
                IsNew = true
            };
            _downloadService.InsertDownload(download);

            //when returning JSON the mime-type must be set to text/plain
            //otherwise some browsers will pop-up a "Save As" dialog.
            return Json(new { success = true, 
                downloadId = download.Id, 
                downloadUrl = Url.Action("DownloadFile", new { downloadGuid = download.DownloadGuid }) });
        }

        #endregion
    }
}

Research.Web/Controllers/PictureController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Research.Core;
using Research.Infrastructure;
using Research.Services.Media;

namespace Research.Web.Controllers
{
    public partial class PictureController : BaseAdminController
    {
        private readonly IPictureService _pictureService;
        private readonly IResearchFileProvider _fileProvider;

        public PictureController(IPictureService pictureService,
            IResearchFileProvider fileProvider)
        {
            this._pictureService = pictureService;
            this._fileProvider = fileProvider;
        }

        [HttpPost]
        //do not validate request token (XSRF)
       // [AdminAntiForgery(true)] 
        public virtual IActionResult AsyncUpload()
        {
            //if (!_permissionService.Authorize(StandardPermissionProvider.UploadPictures))
            //    return Json(new { success = false, error = "You do not have required permissions" }, "text/plain");

            var httpPostedFile = Request.Form.Files.FirstOrDefault();
            if (httpPostedFile == null)
            {
                return Json(new
                {
                    success = false,
                    message = "No file uploaded",
                    downloadGuid = Guid.Empty
                });
            }

            var fileBinary = httpPostedFile.GetDownloadBits();

            const string qqFileNameParameter = "qqfilename";
            var fileName = httpPostedFile.FileName;
            if (string.IsNullOrEmpty(fileName) && Request.Form.ContainsKey(qqFileNameParameter))
                fileName = Request.Form[qqFileNameParameter].ToString();
            //remove path (passed in IE)
            fileName = _fileProvider.GetFileName(fileName);

            var contentType = httpPostedFile.ContentType;

            var fileExtension = _fileProvider.GetFileExtension(fileName);
            if (!string.IsNullOrEmpty(fileExtension))
                fileExtension = fileExtension.ToLowerInvariant();

            //contentType is not always available 
            //that's why we manually update it here
            //http://www.sfsu.edu/training/mimetype.htm
            if (string.IsNullOrEmpty(contentType))
            {
                switch (fileExtension)
                {
                    case ".bmp":
                        contentType = MimeTypes.ImageBmp;
                        break;
                    case ".gif":
                        contentType = MimeTypes.ImageGif;
                        break;
                    case ".jpeg":
                    case ".jpg":
                    case ".jpe":
                    case ".jfif":
                    case ".pjpeg":
                    case ".pjp":
                        contentType = MimeTypes.ImageJpeg;
                        break;
                    case ".png":
                        contentType = MimeTypes.ImagePng;
                        break;
                    case ".tiff":
                    case ".tif":
                        contentType = MimeTypes.ImageTiff;
                        break;
                    default:
                        break;
                }
            }

            var picture = _pictureService.InsertPicture(fileBinary, contentType, null);

            //when returning JSON the mime-type must be set to text/plain
            //otherwise some browsers will pop-up a "Save As" dialog.
            return Json(new { success = true, pictureId = picture.Id, imageUrl = _pictureService.GetPictureUrl(picture, 100) });
        }

        public virtual IActionResult AsyncPdfUpload()
        {
            //if (!_permissionService.Authorize(StandardPermissionProvider.UploadPictures))
            //    return Json(new { success = false, error = "You do not have required permissions" }, "text/plain");

            var httpPostedFile = Request.Form.Files.FirstOrDefault();
            if (httpPostedFile == null)
            {
                return Json(new
                {
                    success = false,
                    message = "No file uploaded",
                    downloadGuid = Guid.Empty
                });
            }

            var fileBinary = httpPostedFile.GetDownloadBits();

            var contentType = httpPostedFile.ContentType;

            if (string.IsNullOrEmpty(contentType))
            {
                 contentType = MimeTypes.ApplicationPdf;
            }

            var pdf = _pictureService.InsertPicture(fileBinary, contentType, null);

            //when returning JSON the mime-type must be set to text/plain
            //otherwise some browsers will pop-up a "Save As" dialog.
            return Json(new { success = true, pictureId = pdf.Id, imageUrl = _pictureService.GetPdfUrl(pdf) });
        }
    }
}

Research.Web/Views/Shared/EditorTemplates/Address.cshtml
@model AddressModel


<input asp-for="Id" type="hidden" />

<div class="form-group">
    <div class="col-md-3">
        <nop-label asp-for="Address1" />
    </div>
    <div class="col-md-9">
        <nop-editor asp-for="Address1" asp-required="true"/>
        <span asp-validation-for="Address1"></span>
    </div>
</div>


<div class="form-group">
    <div class="col-md-3">
        <nop-label asp-for="Address2" />
    </div>
    <div class="col-md-9">
        <nop-editor asp-for="Address2" />
        <span asp-validation-for="Address2"></span>
    </div>
</div>
<div class="form-group">
    <div class="col-md-3">
        <nop-label asp-for="ProvinceId" />
    </div>
    <div class="col-md-9">
        <nop-select asp-for="ProvinceId" asp-items="Model.AvailableProvinces" />
        <span asp-validation-for="ProvinceId"></span>
    </div>
</div>
<div class="form-group">
    <div class="col-md-3">
        <nop-label asp-for="ZipCode" />
    </div>
    <div class="col-md-9">
        <nop-editor asp-for="ZipCode" />
        <span asp-validation-for="ZipCode"></span>
    </div>
</div>

Research.Web/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@((Model > DateTime.MinValue ? Model : DateTime.Today).ToShortDateString())" />
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoDatePicker();
    });
</script>

Research.Web/Views/Shared/EditorTemplates/DateNullable.cshtml
@model DateTime?
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@(Model > DateTime.MinValue || Model.HasValue ? Model.Value.ToShortDateString() : null)" />
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoDatePicker();
    });
</script>

Research.Web/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime
@using System.Globalization
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@((Model > DateTime.MinValue ? Model : DateTime.Today).ToString(CultureInfo.CurrentCulture.DateTimeFormat))" />
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoDateTimePicker({
            popup: {
                position: "bottom right",
                origin: "top right"
            }
        });
    });
</script>

Research.Web/Views/Shared/EditorTemplates/DateTimeNullable.cshtml
@model DateTime?
@using System.Globalization
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@(Model > DateTime.MinValue || Model.HasValue ? Model.Value.ToString(CultureInfo.CurrentCulture.DateTimeFormat) : null)" />
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoDateTimePicker({
            popup: {
                position: "bottom right",
                origin: "top right"
            }
        });
    });
</script>

Research.Web/Views/Shared/EditorTemplates/Download.cshtml
@model int
@inject IDownloadService downloadService

@using Research.Core;
@using Research.Services.Media
@using Research.Web.Framework.UI;
<environment names="Development">
    <link rel="stylesheet" href="~/lib/fineuploader/fineuploader-4.2.2.min.css" asp-append-version="true">
    <script src="~/lib/fineuploader/jquery.fineuploader-4.2.2.min.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <link rel="stylesheet" href="~/lib/fineuploader/fineuploader-4.2.2.min.css" asp-append-version="true">
    <script src="~/lib/fineuploader/jquery.fineuploader-4.2.2.min.js" asp-append-version="true"></script>
</environment>
@{
    //register CSS and JS
    //Html.AddCssFileParts("~/lib/fineuploader/fineuploader-4.2.2.min.css");
    //Html.AddScriptParts("~/lib/fineuploader/jquery.fineuploader-4.2.2.min.js");

    //other variables
    var randomNumber = CommonHelper.GenerateRandomInteger();
    var clientId = "download" + randomNumber;
    var download = downloadService.GetDownloadById(Model);

    var disableUrl = Convert.ToBoolean(ViewData["nop.DownloadEditor.DisableUrl"] ?? false);
}

<script>
    $(document).ready(function () {
        $('#cbUseDownloadURL@(randomNumber)').click(toggleDownloadRecordType@(randomNumber));

        $('#saveDownloadUrl@(randomNumber)').click(function () {
            var downloadUrl = $("#downloadurl@(randomNumber)").val();
            $('#saveDownloadUrl@(randomNumber)').attr('disabled', true);
            $.ajax({
                cache: false,
                type: "POST",
                url: "@(Url.Action("SaveDownloadUrl", "Download", new { area = "Admin" }))",
                data: { "downloadUrl": downloadUrl },
                success: function (data) {
                    $('#pnlDownloadURLResult@(randomNumber)').fadeIn("slow").delay(1000).fadeOut("slow");
                    $("#@(clientId + "value") input").val(data.downloadId);
                    $('#saveDownloadUrl@(randomNumber)').attr('disabled', false);

                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to save download object.');
                    $('#saveDownloadUrl@(randomNumber)').attr('disabled', false);
                }
            });
        });

        toggleDownloadRecordType@(randomNumber)();
    });

    function toggleDownloadRecordType@(randomNumber)() {
        if ($('#cbUseDownloadURL@(randomNumber)').is(':checked')) {
            $('#pnlDownloadURL@(randomNumber)').show();
            $('#pnlDownloadFile@(randomNumber)').hide();
        } else {
            $('#pnlDownloadURL@(randomNumber)').hide();
            $('#pnlDownloadFile@(randomNumber)').show();
        }
    }

</script>

<div id="@(clientId + "value")">
    <input type="hidden" asp-for="@Model" />
</div>

<div class="panel panel-default">
    <div class="panel-body">
        @if (!disableUrl)
        {
            <div class="form-group">
                <div class="col-xs-4">
                    <div class="label-wrapper">
                        <label class="control-label">
                            ใช้ดาวน์โหลด URL
                        </label>
                    </div>
                </div>
                <div class="col-xs-8">
                    <input type="checkbox" name="cbUseDownloadURL@(randomNumber)" id="cbUseDownloadURL@(randomNumber)"
                           @if (download != null && download.UseDownloadUrl) { <text> checked="checked" </text> } />
                </div>
            </div>
        }
        <div id="pnlDownloadURL@(randomNumber)">
            <div class="form-group">
                <div class="col-xs-4">
                    <div class="label-wrapper">
                        <label class="control-label">
                            ดาวน์โหลด URL
                        </label>
                    </div>
                </div>
                <div class="col-xs-8">
                    <input type="text" class="form-control" name="downloadurl@(randomNumber)" id="downloadurl@(randomNumber)"
                           @if (download != null && !string.IsNullOrEmpty(download.DownloadUrl)) { <text> value="@(download.DownloadUrl)" </text> } />
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-8 col-xs-offset-4">
                    <button type="button" id="saveDownloadUrl@(randomNumber)" class="btn btn-primary">บันทึก URL</button>
                    <div id="pnlDownloadURLResult@(randomNumber)" style="display: none;">บันทึก URL</div>
                </div>
            </div>
        </div>
        <div class="form-group" id="pnlDownloadFile@(randomNumber)">
            <div class="col-xs-4">
                <div class="label-wrapper">
                    <label class="control-label">
                        อัพโหลดไฟล์
                    </label>
                </div>
            </div>
            <div class="col-xs-8">
                @*fine uploader container*@
                <div id="@clientId">
                    <noscript>
                        <p>
                            Please enable JavaScript to use file uploader.
                        </p>
                        <!-- or put a simple form for upload here -->
                    </noscript>
                </div>
                @*fine uploader template (keep it synchronized to \Content\fineuploader\templates\default.html)*@
                <script type="text/template" id="@(clientId)-qq-template">
                    <div class="qq-uploader-selector qq-uploader">
                        <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                            <span>ลบไฟล์</span>
                        </div>
                        <div class="qq-upload-button-selector qq-upload-button">
                            <div>อัพโหลด</div>
                        </div>
                        <span class="qq-drop-processing-selector qq-drop-processing">
                            <span>กำลังดำเนินการ</span>
                            <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
                        </span>
                        <ul class="qq-upload-list-selector qq-upload-list">
                            <li>
                                <div class="qq-progress-bar-container-selector">
                                    <div class="qq-progress-bar-selector qq-progress-bar"></div>
                                </div>
                                <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                                <span class="qq-edit-filename-icon-selector qq-edit-filename-icon"></span>
                                <span class="qq-upload-file-selector qq-upload-file"></span>
                                <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                                <span class="qq-upload-size-selector qq-upload-size"></span>
                                <a class="qq-upload-cancel-selector qq-upload-cancel" href="#">ยกเลิก</a>
                                <a class="qq-upload-retry-selector qq-upload-retry" href="#">ลองใหม่อีกครั้ง</a>
                                <a class="qq-upload-delete-selector qq-upload-delete" href="#">ลบ</a>
                                <span class="qq-upload-status-text-selector qq-upload-status-text"></span>
                            </li>
                        </ul>
                    </div>
                </script>

                <script>

                    $(document).ready(function () {
                        $("#@clientId").fineUploader({
                            request: {
                                endpoint: '@(Url.Action("AsyncUpload", "Download", new { area = "Admin" }))'
                            },
                            template: "@(clientId)-qq-template",
                            multiple: false
                        }).on("complete", function (event, id, name, responseJSON, xhr) {
                            $("#@(clientId + "downloadurl")").html("<a class='btn btn-default margin-t-5' href='" + responseJSON.downloadUrl + "'><i class='fa fa-download'></i>ดาวน์โหลดไฟล์</a>");
                            $("#@(clientId + "value") input").val(responseJSON.downloadId);
                            $("#@(clientId + "remove")").show();
                        });


                        $("#@(clientId + "remove")").click(function (e) {
                            $("#@(clientId + "downloadurl")").html("");
                            $("#@(clientId + "value") input").val(0);
                            $(this).hide();
                        });
                    });

                </script>
                <div style="clear: both;">
                    <div id="@(clientId + "downloadurl")" class="pull-left margin-r-5">
                        @if (download != null)
                        {
                            <a class='btn btn-default margin-t-5' href="@(Url.Action("DownloadFile", "Download", new { downloadGuid = download.DownloadGuid, area = "Admin" }))"><i class='fa fa-download'></i>ดาวน์โหลดไฟล์</a>
                        }
                    </div>
                    <div class="pull-left">
                        @if (download != null)
                        {
                            <span id="@(clientId + "remove")" class="btn btn-default margin-t-5"><i class="fa fa-trash"></i>ลบไฟล์</span>
                        }
                        else
                        {
                            <span id="@(clientId + "remove")" class="btn btn-default margin-t-5" style="display:none;"><i class="fa fa-trash"></i>ลบไฟล์</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Research.Web/Views/Shared/EditorTemplates/Picture.cshtml
@model int
@inject IPictureService pictureService

@using Research.Core;
@using Research.Enum;
@using Research.Services.Media
@using Research.Web.Framework.UI;
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/fineuploader/fineuploader-4.2.2.min.css" asp-append-version="true">
        <script src="~/lib/fineuploader/jquery.fineuploader-4.2.2.min.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/fineuploader/fineuploader-4.2.2.min.css" asp-append-version="true">
        <script src="~/lib/fineuploader/jquery.fineuploader-4.2.2.min.js" asp-append-version="true"></script>
    </environment>
    @{
        //register CSS and JS
        //Html.AddCssFileParts("~/lib/fineuploader/fineuploader-4.2.2.min.css");
        //Html.AddScriptParts("~/lib/fineuploader/jquery.fineuploader-4.2.2.min.js");

        //other variables
        var random = CommonHelper.GenerateRandomInteger();
        var clientId = "picture" + random;
        var picture = pictureService.GetPictureById(Model);

        const int pictureSize = 100;
    }

    <div id="@(clientId + "value")">
        <input type="hidden" asp-for="@Model" />
    </div>
    <div class="row">
        <div class="col-md-12">
            <div id="@(clientId + "image")" class="uploaded-image">
                <img src="@(pictureService.GetPictureUrl(Model, pictureSize, true))" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @*fine uploader container*@
            <div id="@clientId" class="upload-image-button pull-left margin-t-5">
                <noscript>
                    <p>Please enable JavaScript to use file uploader.</p>
                </noscript>
            </div>
            <div class="remove-image-button pull-left margin-t-5">
                @if (picture != null)
                {
                    <span id="@(clientId + "remove")" class="btn bg-red">ลบรูป</span>
                }
                else
                {
                    <span id="@(clientId + "remove")" class="btn bg-red" style="display: none;">ลบรูป</span>
                }
            </div>
        </div>
    </div>

    @*fine uploader template (keep it synchronized to \Content\fineuploader\templates\default.html)*@
    <script type="text/template" id="@(clientId)-qq-template">
        <div class="qq-uploader-selector qq-uploader">
            <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                <span>DropFiles</span>
            </div>
            <div class="qq-upload-button-selector qq-upload-button">
                <div>อัพโหลดรูป</div>
            </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>กรุณาเลือกไฟล์</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
            <ul class="qq-upload-list-selector qq-upload-list">
                <li>
                    <div class="qq-progress-bar-container-selector">
                        <div class="qq-progress-bar-selector qq-progress-bar"></div>
                    </div>
                    <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                    <span class="qq-edit-filename-icon-selector qq-edit-filename-icon"></span>
                    <span class="qq-upload-file-selector qq-upload-file"></span>
                    <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                    <span class="qq-upload-size-selector qq-upload-size"></span>
                    <a class="qq-upload-cancel-selector qq-upload-cancel" href="#">ยกเลิก</a>
                    <a class="qq-upload-retry-selector qq-upload-retry" href="#">พยายามอีกครั้ง</a>
                    <a class="qq-upload-delete-selector qq-upload-delete" href="#">ลบรูป</a>
                    <span class="qq-upload-status-text-selector qq-upload-status-text"></span>
                </li>
            </ul>
        </div>
    </script>
    <script>
    $(document).ready(function() {
        $("#@(clientId)").fineUploader({
            request: {
                endpoint: '@(Url.Content("~/Picture/AsyncUpload"))'
            },
            template: "@(clientId)-qq-template",
            multiple: false
        }).on("complete", function(event, id, name, responseJSON, xhr) {
            if (responseJSON.success) {
                $("#@(clientId + "image")").html("<img src='" + responseJSON.imageUrl + "'/>");
                $("#@(clientId + "value") input").val(responseJSON.pictureId);
                $("#@(clientId + "remove")").show();
            }
        });
        $("#@(clientId + "remove")").click(function(e) {
            $("#@(clientId + "image")").html("<img src='@pictureService.GetDefaultPictureUrl(pictureSize,PictureType.Avatar,@"/")'/>");
            $("#@(clientId + "value") input").val(0);
            $(this).hide();
        });
    });
    </script>