Research.Web/Controllers/ResearcherController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Research.Data;
using Research.Services;
using Research.Services.Logging;
using Research.Services.Media;
using Research.Services.Security;
using Research.Web.Factories;
using Research.Web.Extensions;
using Research.Web.Framework.Mvc.Filters;
using Research.Web.Models.Researchers;
using Research.Services.Common;
using Research.Web.Framework.Mvc;
using Research.Web.Models.Common;
using Research.Services.Researchers;
using System.Collections.Generic;
using Research.Core;

namespace Research.Web.Controllers
{
    public partial class ResearcherController : BaseAdminController
    {
        #region Fields

        private readonly IUserActivityService _userActivityService;
        private readonly IUserService _userService;
        private readonly IPermissionService _permissionService;
        private readonly IResearcherModelFactory _researcherModelFactory;
        private readonly IResearcherService _researcherService;
        private readonly IPictureService _pictureService;
        private readonly IAddressService _addressService;
        private readonly IAcademicRankService _academicRankService;
        private readonly IWorkContext _workContext;

        #endregion Fields

        #region Ctor

        public ResearcherController(IUserActivityService userActivityService,
            IUserService userService,
            IPermissionService permissionService,
            IResearcherModelFactory researcherModelFactory,
            IResearcherService researcherService,
            IPictureService pictureService,
            IAddressService addressService,
            IAcademicRankService academicRankService,
            IWorkContext workContext)
        {
            this._userActivityService = userActivityService;
            this._userService = userService;
            this._permissionService = permissionService;
            this._researcherModelFactory = researcherModelFactory;
            this._researcherService = researcherService;
            this._pictureService = pictureService;
            this._addressService = addressService;
            this._academicRankService = academicRankService;
            this._workContext = workContext;
        }

        #endregion

        #region Utilities

        [HttpPost]
        public virtual IActionResult ResearchersSelect()
        {
            //var model = new List<SelectListItem>();
            var model = new List<string>();
            var researchers = _researcherService.GetAllResearchers().ToList();
            foreach (var x in researchers)
            {
                string title = (x.Title != null) ? x.Title.TitleNameTH : string.Empty;
                //model.Add(new SelectListItem(item.Id.ToString(), $"{item.FirstName} {item.LastName}"));
                model.Add($"{title}{x.FirstName} {x.LastName}");
            }
            return Json(model);
        }

        [HttpGet, ActionName("GetAcademicRanksByPersonalTypeId")]
        public virtual IActionResult GetAcademicRanksByPersonalTypeId(string personalTypeId, bool? addSelectPersonalTypeItem)
        {
            //permission validation is not required here

            // This action method gets called via an ajax request
            if (string.IsNullOrEmpty(personalTypeId))
                throw new ArgumentNullException(nameof(personalTypeId));
            int id = Int32.Parse(personalTypeId);
            var result = _academicRankService.GetAcademicRanksByPersonalTypeId(id)
                                .Select(x => new { id = x.Id, name = x.NameTh }).ToList();

            return Json(result);
        }


        #endregion

        #region List

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageResearchers))
                return AccessDeniedView();

            //prepare model
            var model = _researcherModelFactory.PrepareResearcherSearchModel(new ResearcherSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult List(ResearcherSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageResearchers))
                return AccessDeniedKendoGridJson();

            if (_workContext.CurrentUser.UserTypeId == 2) //Researchers Role will see only owner researcher information
                searchModel.Email = _workContext.CurrentUser.Email;
            //prepare model
            var model = _researcherModelFactory.PrepareResearcherListModel(searchModel);

            return Json(model);
        }

        #endregion

        #region Create / Edit / Delete
        [HttpGet, ActionName("Create")]
        public virtual IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageResearchers))
                return AccessDeniedView();

            //prepare model
            var model = _researcherModelFactory.PrepareResearcherModel(new ResearcherModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Create(ResearcherModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageResearchers))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {

                var researcher = model.ToEntity<Researcher>();

                if (model.ParseDateOfBirth() != null)
                    researcher.Birthdate = model.ParseDateOfBirth();
                researcher.IsActive = true;
                _researcherService.InsertResearcher(researcher);

                var address = model.AddressModel.ToEntity<Address>();
                SaveAddress(model.AddressModel, address);
                if (address.Id != 0)
                {
                    researcher.AddressId = address.Id;
                    _researcherService.UpdateResearcher(researcher);
                }


                SuccessNotification("Admin.ContentManagement.Researchers.Added");

                //activity log
                //_userActivityService.InsertActivity("AddNewResearcher", "ActivityLog.AddNewResearcher", researcher);

                if (!continueEditing)
                    return RedirectToAction("List");

                //selected tab
                SaveSelectedTabName();

                return RedirectToAction("Edit", new { id = researcher.Id });
            }

            //prepare model
            model = _researcherModelFactory.PrepareResearcherModel(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        private void SaveAddress(AddressModel model, Address address)
        {
            if ((model != null) && (address.Id == 0))
            {
                if (!string.IsNullOrEmpty(model.Address1) ||
                    !string.IsNullOrEmpty(model.Address2) ||
                    !string.IsNullOrEmpty(model.ZipCode) ||
                    model.ProvinceId != 0)
                _addressService.InsertAddress(address);
            }
            else
            {
                var addr = _addressService.GetAddressById(address.Id);
                addr.Address1 = model.Address1;
                addr.Address2 = model.Address2;
                addr.ProvinceId = model.ProvinceId;
                addr.ZipCode = model.ZipCode;
                _addressService.UpdateAddress(addr);
            }
        }

        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageResearchers))
                return AccessDeniedView();

            //try to get a researcher with the specified id
            var researcher = _researcherService.GetResearcherById(id);
            if (researcher == null)
                return RedirectToAction("List");

            //prepare model
            var model = _researcherModelFactory.PrepareResearcherModel(null, researcher);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Edit(ResearcherModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageResearchers))
                return AccessDeniedView();

            //try to get a researcher with the specified id
            var researcher = _researcherService.GetResearcherById(model.Id);
            bool active = researcher.IsActive;
            bool completed = researcher.IsCompleted;
            if (researcher == null)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                researcher = model.ToEntity(researcher);
                researcher.IsActive = active;
                researcher.IsCompleted = completed;
                if (model.ParseDateOfBirth() != null)
                    researcher.Birthdate = model.ParseDateOfBirth();

                _researcherService.UpdateResearcher(researcher);

                var address = model.AddressModel.ToEntity<Address>();
                SaveAddress(model.AddressModel, address);
                if (address.Id != 0)
                {
                    researcher.AddressId = address.Id;
                    _researcherService.UpdateResearcher(researcher);
                }

                SuccessNotification("Researcher Updated");

                //activity log
                //_userActivityService.InsertActivity("EditResearcher", "ActivityLog EditResearcher", researcher);

                if (!continueEditing)

Research.Web/Views/Researcher/Add.cshtml
@model ResearcherModel

@{    
    //page title
    ViewBag.Title = "เพิ่มรายการนักวิจัย";
}

<form asp-controller="Researcher" asp-action="Create" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            เพิ่มรายการนักวิจัย
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">กลับสู่หน้ารายการข้อมูลผู้วิจัย</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึก
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึกและทำรายการต่อ
            </button>
            
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

Research.Web/Views/Researcher/Create.cshtml
@model ResearcherModel

@{    
    //page title
    ViewBag.Title = "เพิ่มรายการนักวิจัย";
}

<form asp-controller="Researcher" asp-action="Create" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            เพิ่มรายการนักวิจัย
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">กลับสู่หน้ารายการข้อมูลผู้วิจัย</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึก
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึกและทำรายการต่อ
            </button>
            
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

Research.Web/Views/Researcher/Edit.cshtml
@model ResearcherModel

@{
    //page title
    ViewBag.Title = "รายละเอียดข้อมูลนักวิจัย";
}

<form asp-controller="Researcher" asp-action="Edit" method="post">
    
    <div class="content-header clearfix">
        <h1 class="pull-left">
            ข้อมูลนักวิจัย
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">กลับสู่หน้ารายการข้อมูลผู้วิจัย</a>
            </small>
        </h1>
        <div class="pull-right">
            @*<a asp-action="Delete" class="btn bg-red">
                <input asp-for="Id" type="hidden" />
                <i class="fa fa-trash-o"></i>
                ลบรายการ
            </a>*@
        </div>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึก
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึกและทำรายการต่อ
            </button>

        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="nop-delete" />

Research.Web/Views/Researcher/Info.cshtml
@model ResearcherModel

@{
    //page title
    ViewBag.Title = "รายละเอียดข้อมูลนักวิจัย";
}

<form asp-controller="Researcher" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            ข้อมูลนักวิจัย
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">กลับสู่หน้ารายการข้อมูลผู้วิจัย</a>
            </small>
        </h1>
        <div class="pull-right">
            <span id="researcher-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                ลบรายการ
            </span>
        </div>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึก
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                บันทึกและทำรายการต่อ
            </button>

        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="nop-delete" />

Research.Web/Views/Researcher/List.cshtml
@model ResearcherSearchModel

@{
    //page title
    ViewBag.Title = "ข้อมูลนักวิจัย";
}

<div class="content-header clearfix">
    <h1 class="pull-left">
        ข้อมูลนักวิจัย
    </h1>
    @*<div class="pull-right">
        <a asp-action="Create" class="btn bg-blue">
            <i class="fa fa-plus-square"></i>
            เพิ่มรายการนักวิจัย
        </a>
    </div>*@
</div>

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default panel-search">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="FirstName" />
                                </div>
                                <div class="col-md-8">
                                    <nop-editor asp-for="FirstName" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="LastName" />
                                </div>
                                <div class="col-md-8">
                                    <nop-editor asp-for="LastName" />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="button" id="search-researchers" class="btn btn-primary btn-search">
                                        <i class="fa fa-search"></i>
                                        ค้นหา
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="AgencyId" />
                                </div>
                                <div class="col-md-8">
                                    <nop-select asp-for="AgencyId" asp-items="Model.AvailableAgencies" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="PersonTypeId" />
                                </div>
                                <div class="col-md-8">
                                    <nop-select asp-for="PersonTypeId" asp-items="Model.AvailablePersonTypes" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="IsCompleted" />
                                </div>
                                <div class="col-md-8">
                                    <nop-select asp-for="IsCompleted" asp-items="Model.AvailableActiveStatues" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="researchers-grid"></div>

                    <script>
                        $(document).ready(function () {
                            $("#researchers-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("List", "Researcher"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: function() {
                                                var data = {
                                                    FirstName: $('#FirstName').val(),
                                                    LastName: $('#LastName').val(),
                                                    AgencyId: $('#AgencyId').val(),
                                                    PersonTypeId: $('#PersonTypeId').val(),
                                                    IsCompleted: $('#IsCompleted').val(),
                                                };
                                                //addAntiForgeryToken(data);
                                                return data;
                                            }
                                        }
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors"
                                    },
                                    error: function (e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    pageSize: @(Model.PageSize),
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                pageable: {
                                    refresh: true,
                                    pageSizes: [@(Model.AvailablePageSizes)],
                                    @await Html.PartialAsync("_GridPagerMessages")
                                },
                                editable: {
                                    confirmation: "คุณต้องการลบรายการนี้ใช่หรือไม่",
                                    mode: "inline"
                                },
                                scrollable: false,
                                columns: [
                                {
                                    field: "ResearcherCode",
                                    title: "รหัสนักวิจัย",
                                    width: 150,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                }, {
                                    field: "FirstName",
                                    title: "ชื่อ",
                                    width: 150,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                }, {
                                    field: "LastName",
                                    title: "นามสกุล",
                                    width: 150,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                }, {
                                    field: "AgencyName",
                                    title: "หน่วยงาน",
                                    width: 200,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                }, {
                                    field: "PersonalTypeName",
                                    title: "ประเภทบุคลากร",
                                    width: 150,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                }, {
                                    field: "IsCompleted",
                                    title: "สถานะเข้าใช้งาน",
                                    width: 110,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '# if(IsCompleted) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                }, {
                                    field: "Id",
                                    title: "การกระทำ",
                                    width: 150,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '<a class="btn btn-default" href="/Researcher/Edit/#=Id#"><i class="fa fa-pencil"></i></a> <a class="btn btn-default" href="/Researcher/View/#=Id#" target="_blank"><i class="fa fa-eye"></i></a>'                                }
                                ]
                            });
                        });
                    </script>

                    <script>
                        $(document).ready(function () {
                            //search button
                            $('#search-researchers').click(function () {
                                //search
                                var grid = $('#researchers-grid').data('kendoGrid');
                                grid.dataSource.read();
                                return false;
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

Research.Web/Views/Researcher/View.cshtml
@model ResearcherModel

@inject IPictureService pictureService
@{
    ViewData["Title"] = "รายละเอียดนักวิจัย";
    Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>รายละเอียดนักวิจัย</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <environment names="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </environment>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
    </style>
</head>
<body class="py-4">
    <div class="container">

        <form>
            <div class="alert alert-primary"><h5>ข้อมูลส่วนตัว</h5></div>
            <img src="@(pictureService.GetPictureUrl(@Model.PictureId.Value, 200, true))" class="rounded float-right" >
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">ชื่อนักวิจัย</label>
                <div class="col-sm-9">
                    <label class="col-sm-9 col-form-label">@Model.FullName</label>
                    <label class="col-sm-9 col-form-label">@Model.FirstNameEN @Model.LastNameEN</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">เลขประจำตัวประชาชน</label>
                <div class="col-sm-9">
                    <label class="col-sm-9 col-form-label">@Model.IDCard</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">วันเดือนปีเกิด</label>
                <div class="col-sm-9">
                    <label class="col-sm-9 col-form-label">@Model.DateOfBirthName</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">ประเภทบุคลากร</label>
                <div class="col-sm-9">
                    <label class="col-sm-9 col-form-label">@Model.PersonalTypeName</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">ตำแหน่งทางวิชาการ</label>
                <div class="col-sm-9">
                    <label class="col-sm-9 col-form-label">@Model.AcademicRankName</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">หน่วยงานหลัก</label>
                <div class="col-sm-9">
                    <label class="col-sm-9 col-form-label">@Model.AgencyName</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">โทรศัพท์</label>
                <div class="col-sm-9">
                    <label class="col-sm-9 col-form-label">@Model.Telephone</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">อีเมล</label>
                <div class="col-sm-9">
                    <label class="col-sm-9 col-form-label">@Model.Email</label>
                </div>
            </div>
            <div class="alert alert-primary"><h5>ที่อยู่สามารถติดต่อได้สะดวก</h5></div>
            <div class="form-group row">
                <label class="col-sm-12 col-form-label">@Model.AddressModel.Address1 @Model.AddressModel.Address2</label>
                <label class="col-sm-12 col-form-label">จังหวัด @Model.AddressModel.ProvinceName รหัสไปรษณีย์ @Model.AddressModel.ZipCode</label>
            </div>
            <div class="alert alert-primary"><h5>ข้อมูลการศึกษา</h5></div>
            <div class="form-group row">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">ระดับปริญญา</th>
                            <th scope="col">วุฒิการศึกษา</th>
                            <th scope="col">สถาบันการศึกษา</th>
                            <th scope="col">ประเทศ</th>
                            <th scope="col">ปีการศึกษาที่จบ</th>
                        </tr>
                    </thead>
                    @foreach (var x in @Model.ResearcherEducationListModel.Data.ToList())
                    {
                        <tbody>
                            <tr>
                                <td>@x.DegreeName</td>
                                <td>@x.EducationLevelName</td>
                                <td>@x.InstituteName</td>
                                <td>@x.CountryName</td>
                                <td>@x.GraduationYear</td>
                            </tr>
                        </tbody>
                    }
                </table>
            </div>
        </form>


    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Research.Web/Views/Researcher/_CreateOrUpdate.Addr.cshtml
@model ResearcherModel

<div asp-validation-summary="ModelOnly"></div>


<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">

                <div class="panel-body">
                    <nop-editor asp-for="AddressModel" asp-template="Address" />
                </div>
            </div>
        </div>
    </div>
</div>